### ISSUE TITLE
support TOS

### ISSUE THREAD

**Issue by smallnest** [mdlayher/icmpx#1]
We should set tos in some cases, so could you add a function to set TOS?

**Comment by mdlayher** [comment]
Do you want the ability to set the option at bind time via a Config argument, or as a method to change it on the fly on one of the Conn types?

**Comment by smallnest** [comment]
I think the second(add a method and invoke it as necessary) may be better because many users don't need tos setting

**Comment by mdlayher** [comment]
Done: 626d638b9ae82abce4067151c5a5db75a61c70bc.
